### PR TITLE
support {param} style and and array query params 

### PR DESCRIPTION
**Pull request by philip1986**
Would solve https://github.com/rricard/koa-swagger/issues/2

### CODE REVIEW

**Comment by philip1986** [comment]
@theomega could you please fix the lint errors

**Comment by theomega** [comment]
@philip1986 done

**Comment by rricard** [comment]
Seems good to me: thanks!

**Comment by philip1986** [comment]
@rricard could you please also make a npm release including this fix?

**Comment by rricard** [comment]
@philip1986 oh yea, sorry!

**Comment by rricard** [comment]
0.3.0 published!

**Comment by rricard** [comment]
@philip1986 can you give me your npm username ? So you can then publish new versions, I also added you as a contributor, you may maintain the project more than me since I'm not actively using it and you are! ;)

**Comment by philip1986** [comment]
@rricard tanks a lot. My npm user name is also philip1986.

**Pull request merged**
